name: test-javascript

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version: ['18.x', '20.x']
        include:
          - os: windows-latest
            node-version: '20.x'
          - os: macos-latest
            node-version: '20.x'
          - os: windows-latest
            node-version: '20.x'
          - os: macos-latest
            node-version: '20.x'

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
      - run: npm run eslint
